title: [ESCU Companion App]
description: [A simple Splunk App developed to make your implementation of Splunk ESCU that much easier.]
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
