title: [ESCU Companion App]
description: [A simple Splunk App developed to make your implementation of Splunk ESCU that much easier.]
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

name: Brandon Sternfield (Optiv + ClearShark)
repository: TheLawsOfChaos/escu_companion
twitter:
  username: thelawsofchaos
twitter_username: thelawsofchaos
github_username: thelawsofchaos

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/thelawsofchaos"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/TheLawsOfChaos/escu_companion"
